language: cpp

sudo: required

compiler:
  - gcc

before_script:
  - cmake .

script:
  - make
  && FILE="`find . -maxdepth 1 -type f -perm -001`"
  && echo $FILE
  && time $FILE
  && echo $?
  ;

branches:
  only:
    - master

env:
  - LANG="en_US.UTF-8"

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         wget http://www.cmake.org/files/v3.3/cmake-3.3.0-Linux-i386.tar.gz
      && tar -xzf cmake-3.3.0-Linux-i386.tar.gz
      && sudo cp -fR cmake-3.3.0-Linux-i386/* /usr
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    else
         brew update
      && brew unlink cmake
      && brew install cmake
      ;
    fi

os:
  - linux
  - osx
