language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-4.8

sudo: false

compiler:
  - gcc

before_script:
  - cmake .

script:
  - make
    find . -maxdepth 1 -type f -perm -001 -exec {} \;
    echo $?

branches:
  only:
    - master

env:
  - LANG="en_US.UTF-8"

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    else
         brew update
      && brew unlink cmake
      && brew install cmake
      ;
    fi

os:
  - linux
  - osx
